name: Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install
      run: npm ci
    - name: Lint
      run: npm run lint:lib
    - name: Test
      run: npm run test:lib
    - name: Build
      run: npm run build:lib
